name: eco_share
description: EcoShare - Aplicativo de sustentabilidade para doação de itens.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Gerenciamento de estado - Riverpod
  flutter_riverpod: ^2.4.9

  # Consumo de API - Dio
  dio: ^5.4.0

  # Persistência local
  sqflite: ^2.3.0
  path: ^1.8.3

  # Imagens
  image_picker: ^1.0.7

  # Navegação - go_router
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
